[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_APPWRITE_ENDPOINT = "https://nyc.cloud.appwrite.io/v1"
  VITE_APPWRITE_PROJECT_ID = "686813c9002897ec2332"
  VITE_APPWRITE_DATABASE_ID = "transfile-db"
  VITE_APPWRITE_SESSIONS_COLLECTION_ID = "sessions"
  VITE_APPWRITE_FILES_COLLECTION_ID = "files"
  VITE_APPWRITE_BUCKET_ID = "file-storage"
  VITE_API_ENDPOINT = "https://nyc.cloud.appwrite.io/v1"
